---
- name: Nginx Management Playbook
  hosts: laptop
  tasks:
    -
    - name: Install Nginx
      become_user: root
      become_method: sudo
      apt:
        name: nginx
        state: present
      tags:
        - install

