---
- name: Nginx Management Playbook
  hosts: docker_host
  tasks:
    - name: Install Nginx
      become: true
      become_user: root
      become_method: sudo
      apt:
        name: nginx
        state: present
      tags:
        - install

    - name: Update Ngin
      apt:
        name: nginx
        state: latest
      tags:
        - update

    - name: Handle emergency situation for Nginx
      shell: systemctl restart nginx
      ignore_errors: yes
      register: restart_nginx_result
      changed_when: restart_nginx_result is failed
      tags:
        - emergency
